name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Package Electron app
        run: npx electron-packager . "ControlMaquina" --platform=win32 --arch=x64 --out=dist --overwrite

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ControlMaquina
          path: dist/